version: '3.8'

services:
  postgres:
    container_name: postgres-server-gestor-lab
    image: postgres:latest
    volumes:
      - C:\Users\Habby\Desktop\Gestor_Lab\postgres\postgresql:\var\lib\postgresql
      - C:\Users\Habby\Desktop\Gestor_Lab\postgres\postgresql_data:\var\lib\postgresql\data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=password
    restart: always
    ports:
      - 5432:5432

  web:
    container_name: app-web
    image: gestor-lab-app
    build:
      context: .
      dockerfile: ./Dockerfile

    command: >
      sh -c  "python manage.py collectstatic --noinput
              python manage.py makemigrations --noinput
              python manage.py test
              python manage.py migrate --noinput
              python manage.py runserver 0.0.0.0:8001"
    volumes:
      - .:/code
    ports:
      - 8001:8001

networks:
  default:
    external: true
    name: labens-network